<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relationship.proto

namespace Relationship;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Message representing the left hand (dominant) entity.
 * </pre>
 *
 * Protobuf type <code>relationship.RelationshipLeftEntity</code>
 */
class RelationshipLeftEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 leftId = 1;</code>
     */
    private $leftId = 0;

    public function __construct() {
        \GPBMetadata\Relationship::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 leftId = 1;</code>
     */
    public function getLeftId()
    {
        return $this->leftId;
    }

    /**
     * <code>int32 leftId = 1;</code>
     */
    public function setLeftId($var)
    {
        GPBUtil::checkInt32($var);
        $this->leftId = $var;
    }

}

