<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relationship.proto

namespace Relationship;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Response message for performing an operation on a relationship.
 * </pre>
 *
 * Protobuf type <code>relationship.RelationshipResponse</code>
 */
class RelationshipResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     * The ID of the left hand (dominant) entity.
     * </pre>
     *
     * <code>int32 leftId = 1;</code>
     */
    private $leftId = 0;
    /**
     * <pre>
     * The ID of the right hand (related) entity.
     * </pre>
     *
     * <code>int32 rightId = 2;</code>
     */
    private $rightId = 0;
    /**
     * <pre>
     * Was the operation on the successfully completed?
     * </pre>
     *
     * <code>bool success = 3;</code>
     */
    private $success = false;

    public function __construct() {
        \GPBMetadata\Relationship::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     * The ID of the left hand (dominant) entity.
     * </pre>
     *
     * <code>int32 leftId = 1;</code>
     */
    public function getLeftId()
    {
        return $this->leftId;
    }

    /**
     * <pre>
     * The ID of the left hand (dominant) entity.
     * </pre>
     *
     * <code>int32 leftId = 1;</code>
     */
    public function setLeftId($var)
    {
        GPBUtil::checkInt32($var);
        $this->leftId = $var;
    }

    /**
     * <pre>
     * The ID of the right hand (related) entity.
     * </pre>
     *
     * <code>int32 rightId = 2;</code>
     */
    public function getRightId()
    {
        return $this->rightId;
    }

    /**
     * <pre>
     * The ID of the right hand (related) entity.
     * </pre>
     *
     * <code>int32 rightId = 2;</code>
     */
    public function setRightId($var)
    {
        GPBUtil::checkInt32($var);
        $this->rightId = $var;
    }

    /**
     * <pre>
     * Was the operation on the successfully completed?
     * </pre>
     *
     * <code>bool success = 3;</code>
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * <pre>
     * Was the operation on the successfully completed?
     * </pre>
     *
     * <code>bool success = 3;</code>
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;
    }

}

