<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relationship.proto

namespace Relationship;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 * Message representing the right hand (dominant) entity.
 * </pre>
 *
 * Protobuf type <code>relationship.RelationshipRightEntity</code>
 */
class RelationshipRightEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 rightId = 1;</code>
     */
    private $rightId = 0;

    public function __construct() {
        \GPBMetadata\Relationship::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 rightId = 1;</code>
     */
    public function getRightId()
    {
        return $this->rightId;
    }

    /**
     * <code>int32 rightId = 1;</code>
     */
    public function setRightId($var)
    {
        GPBUtil::checkInt32($var);
        $this->rightId = $var;
    }

}

